nav:
  home: /
  discover: /descobreix
  projects: /projectes
  resources: /recursos

home:
  video: 468949821

  unesco:
    programme: https://en.unesco.org/mab
    biosphere_reserve: https://en.unesco.org/biosphere/wnbr
    strategy: https://unesdoc.unesco.org/ark:/48223/pf0000103849_fre
    action_plan: http://www.unesco.org/new/en/natural-sciences/environment/ecological-sciences/man-and-biosphere-programme/strategy-and-action-plan/
    ods: https://www.exteriors.ad/ca/ods
