nav:
  home: /
  discover: /descobreix
  projects: /projectes
  resources: /recursos

home:
  video: 468949821

  unesco:
    programme: https://en.unesco.org/mab
    biosphere_reserve: https://en.unesco.org/biosphere/wnbr
    strategy: https://unesdoc.unesco.org/ark:/48223/pf0000103849_fre
    action_plan: http://www.unesco.org/new/en/natural-sciences/environment/ecological-sciences/man-and-biosphere-programme/strategy-and-action-plan/
    ods: https://www.exteriors.ad/ca/ods

  goals:
    - internationalization
    - sustainability
    - experimentation
    - cooperation
    - anticipation

  tasks:
    - conservation
    - development
    - logistics

discover:
  heritage:
    - id: natural
      text: 1
      image: https://source.unsplash.com/NWncrMbxECU/500x700
      link: https://www.refugisorteny.com/
    - id: cultural
      text: 2
      image: https://source.unsplash.com/E-rbvtOhLNI/500x500
      link: https://www.ordino.ad/turisme/que-visitar/que-visitar
    - id: people
      text: 2
      image: https://source.unsplash.com/nF8xhLMmg0c/600x500
      link: https://www.ordino.ad/ordino
  principles:
    - waste
    - footprint
    - wildlife
    - private
    - users
    - join

# Airtable API config
api:
  base: app8cLkInnlaYQ6Zy
  resources:
    PROJECTS:
      endpoint: projects
      options:
        fields:
          - cover
          - name_ca
          - description_ca
        sort:
          order: asc
        where:
          constraints: 1
          active:
            checked: true

    SOCIAL_PHOTOS:
      endpoint: social_photos
      options:
        max: 10
        fields:
          - username
          - image
        where:
          active:
            checked: true
